import type { Metadata } from 'next';
import './globals.scss';
import LayoutClient from './layout.client';
import { Inter, Montserrat } from 'next/font/google';
import { getLocale, getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const interSans = Inter({
	variable: '--font-inter',
	subsets: ['latin']
});

const montserrat = Montserrat({
	variable: '--font-montserrat-sans',
	subsets: ['latin']
});

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();
	const messages = await getMessages();
	return (
		<html lang={locale} suppressHydrationWarning>
			<body className={`${interSans.variable}  ${montserrat.variable}`}>
				<div className='wrapper'>
					<NextIntlClientProvider messages={messages}>
						<LayoutClient>{children}</LayoutClient>
					</NextIntlClientProvider>
				</div>
			</body>
		</html>
	);
}
